package ru.mirea.callcenter;

import ru.mirea.callcenter.exception.*;
import ru.mirea.callcenter.model.*;
import ru.mirea.callcenter.repository.*;
import ru.mirea.callcenter.service.*;
import ru.mirea.callcenter.util.*;
import java.nio.file.Path;
import java.sql.SQLException;
import java.time.*;
import java.util.*;

public class Main {
    private final Scanner scanner=new Scanner(System.in);
    private final OperatorService operators=new OperatorService(new OperatorRepository());
    private final AppealService appeals=new AppealService(new AppealRepository(),operators);
    public static void main(String[] args) { new Main().run(); }
    private void run() { while(true){try { printMainMenu(); switch(readInt("Выберите действие: ")) {case 1->operatorMenu();case 2->appealMenu();case 3->searchMenu();case 4->filterSortMenu();case 5->System.out.println(appeals.statistics());case 6->export();case 7->showTables();case 0->{System.out.println("До свидания!");return;}default->System.out.println("Нет такого пункта меню.");} }catch(BusinessException|EntityNotFoundException e){System.out.println("Ошибка: "+e.getMessage());}catch(SQLException e){System.out.println("Ошибка базы данных: "+e.getMessage());}catch(Exception e){System.out.println("Ошибка: "+e.getMessage());}} }
    private void printMainMenu(){System.out.println("\n===== СИСТЕМА КОЛЛ-ЦЕНТРА =====\n1. Операторы\n2. Обращения\n3. Поиск обращений\n4. Фильтрация и сортировка\n5. Статистика\n6. Экспорт данных\n7. Вывести таблицы базы данных\n0. Выход");}
    private void operatorMenu()throws SQLException {while(true){System.out.println("\nОПЕРАТОРЫ: 1.Создать 2.Список 3.По ID 4.Изменить 5.Удалить 0.Назад");switch(readInt("Действие: ")){case 1->{Operator o=readOperator(null);System.out.println("Создан оператор ID "+operators.create(o).getId());}case 2->print(operators.getAll());case 3->System.out.println(operators.getById(readInt("ID: ")));case 4->{int id=readInt("ID: ");Operator old=operators.getById(id);operators.update(readOperator(old));System.out.println("Оператор обновлён.");}case 5->{operators.delete(readInt("ID: "));System.out.println("Оператор удалён.");}case 0->{return;}default->System.out.println("Нет такого пункта.");}}}
    private void appealMenu()throws SQLException {while(true){System.out.println("\nОБРАЩЕНИЯ: 1.Создать 2.Список 3.По ID 4.Изменить 5.Сменить статус 6.Удалить 0.Назад");switch(readInt("Действие: ")){case 1->{Appeal a=readAppeal(null);System.out.println("Создано обращение ID "+appeals.create(a).getId());}case 2->print(appeals.getAll());case 3->System.out.println(appeals.getById(readInt("ID: ")));case 4->{int id=readInt("ID: ");Appeal a=readAppeal(appeals.getById(id));appeals.updateDetails(a);System.out.println("Обращение обновлено.");}case 5->{int id=readInt("ID: ");AppealStatus s=readStatus();appeals.changeStatus(id,s);System.out.println("Статус обновлён.");}case 6->{appeals.delete(readInt("ID: "));System.out.println("Обращение удалено.");}case 0->{return;}default->System.out.println("Нет такого пункта.");}}}
    private void searchMenu()throws SQLException {System.out.println("1. По имени/телефону клиента\n2. По теме");int action=readInt("Действие: ");String q=readRequired("Введите запрос: ");if(action==1)print(appeals.searchClient(q));else if(action==2)print(appeals.searchTopic(q));else System.out.println("Нет такого пункта.");}
    private void filterSortMenu()throws SQLException {System.out.println("1. По статусу\n2. По диапазону дат\n3. Сортировка по дате\n4. Сортировка по статусу");switch(readInt("Действие: ")){case 1->print(appeals.filterByStatus(readStatus()));case 2->{LocalDate from=readDate("Дата от (yyyy-MM-dd): ");LocalDate to=readDate("Дата до (yyyy-MM-dd): ");print(appeals.filterByCreatedRange(from.atStartOfDay(),to.atTime(23,59,59)));}case 3->print(appeals.sortByCreatedAt());case 4->print(appeals.sortByStatus());default->System.out.println("Нет такого пункта.");}}
    private void export()throws Exception {List<Appeal> list=appeals.getAll();Path dir=Path.of("exports");new ExcelExporter().export(list,dir.resolve("appeals.xlsx"));new CsvExporter().export(list,dir.resolve("appeals.csv"));System.out.println("Экспортированы файлы exports/appeals.xlsx и exports/appeals.csv");}
    private void showTables()throws SQLException {System.out.println("\nОПЕРАТОРЫ");print(operators.getAll());System.out.println("\nОБРАЩЕНИЯ");print(appeals.getAll());}
    private Operator readOperator(Operator old){String full=readDefault("ФИО",old==null?null:old.getFullName());String login=readDefault("Логин",old==null?null:old.getLogin());String dep=readDefault("Отдел",old==null?null:old.getDepartment());boolean active=readBoolean("Активен (true/false)",old==null||old.isActive());return new Operator(old==null?null:old.getId(),full,login,dep,active);}
    private Appeal readAppeal(Appeal old){Integer op=readNullableInt("ID оператора (пусто, если не назначен)",old==null?null:old.getOperatorId());String name=readDefault("Имя клиента",old==null?null:old.getClientName());String phone=readDefault("Телефон",old==null?null:old.getClientPhone());String topic=readDefault("Тема",old==null?null:old.getTopic());String category=readDefault("Категория TECH/COMPLAINT/CONSULTATION/BILLING",old==null?null:old.getCategory());return new Appeal(old==null?null:old.getId(),op,name,phone,topic,category.toUpperCase(),old==null?AppealStatus.NEW:old.getStatus(),old==null?null:old.getCreatedAt(),old==null?null:old.getClosedAt());}
    private int readInt(String prompt){while(true){System.out.print(prompt);try{return Integer.parseInt(scanner.nextLine().trim());}catch(NumberFormatException e){System.out.println("Ошибка: требуется целое число.");}}}
    private Integer readNullableInt(String prompt,Integer current){System.out.print(prompt+(current==null?": ":" ["+current+"]; '-' снять назначение: "));String s=scanner.nextLine().trim();if(s.isEmpty())return current;if("-".equals(s))return null;try{return Integer.valueOf(s);}catch(NumberFormatException e){System.out.println("Ошибка: требуется целое число.");return readNullableInt(prompt,current);}}
    private String readRequired(String prompt){while(true){System.out.print(prompt);String value=scanner.nextLine().trim();if(!value.isEmpty())return value;System.out.println("Поле не может быть пустым.");}}
    private String readDefault(String name,String current){System.out.print(name+(current==null?": ":" ["+current+"]: "));String s=scanner.nextLine().trim();return s.isEmpty()?current:s;}
    private boolean readBoolean(String prompt,boolean current){while(true){System.out.print(prompt+" ["+current+"]: ");String s=scanner.nextLine().trim();if(s.isEmpty())return current;if("true".equalsIgnoreCase(s)||"false".equalsIgnoreCase(s))return Boolean.parseBoolean(s);System.out.println("Введите true или false.");}}
    private AppealStatus readStatus(){while(true){System.out.print("Статус "+Arrays.toString(AppealStatus.values())+": ");try{return AppealStatus.valueOf(scanner.nextLine().trim().toUpperCase());}catch(IllegalArgumentException e){System.out.println("Некорректный статус.");}}}
    private LocalDate readDate(String prompt){while(true){try{return LocalDate.parse(readRequired(prompt));}catch(Exception e){System.out.println("Введите дату в формате yyyy-MM-dd.");}}}
    private void print(List<?> items){if(items.isEmpty())System.out.println("Записей нет.");else items.forEach(System.out::println);}
}
